// Configuration for EG Comfort app
export const CONFIG = {
  brand: {
    companyName: "Energy Guys Comfort",
    shortName: "EG Comfort",
    domain: "egcomfort.com",
    tagline: "Fix the home, not just the HVAC",
    sub: "Lower bills. Better comfort. Proven results.",
  },

  exampleBill: {
    currentCharges: 180.13,
    monthlyBill: 180.13,
    usageKwhCurrent: 1057,
    energyCharge: 144.81,
    baseFee: 25.00,
    cityTax: 3.53,
    franchiseFee: 6.79,
    avgDailyKwhCurrent: 38,
    avgDailyCostCurrent: 6.06,
    serviceFrom: "02/05/2026",
    serviceTo: "03/05/2026",
    serviceDays: 28,

    priorBill: 314.56,
    usageKwhLastYear: 1982,
    energyChargeLastYear: 271.53,
    baseFeeLastYear: 25.00,
    cityTaxLastYear: 6.17,
    franchiseFeeLastYear: 11.86,
    avgDailyKwhLastYear: 71,
    avgDailyCostLastYear: 10.59,
    serviceFromLastYear: "02/05/2025",
    serviceToLastYear: "03/05/2025",

    kwhReduction: 925,
    dollarSavings: 134.43,
    reductionPercent: 46.7,
    reductionLabel: "47% lower kWh usage vs same month last year",
    dollarSavingsLabel: "$134.43 lower bill vs same month last year",
    billImageUrl: "",
  },

  packages: {
    coreSeal: {
      id: "coreSeal",
      name: "EG Comfort Core Seal",
      price: 3000,
      badge: "Best place to start",
      includes: [
        "Two-system core sealing package",
        "Airflow optimization",
        "Basic performance verification",
      ],
      includedAddons: [],
    },
    performance: {
      id: "performance",
      name: "EG Comfort Performance",
      price: 4198,
      badge: "Most Popular",
      includes: [
        "Everything in Core Seal",
        "Duct cleaning",
        "Boot sealing",
      ],
      includedAddons: ["ductCleaning", "bootSealing"],
    },
    ultimate: {
      id: "ultimate",
      name: "EG Comfort Ultimate",
      price: 6995,
      badge: "Premium Comfort + Control",
      includes: [
        "Everything in Performance",
        "2 smart thermostats",
        "3 room sensors",
        "2 upgraded 4-inch filter/plenum upgrades",
        "Emporia energy monitor",
      ],
      includedAddons: ["ductCleaning", "bootSealing", "emporiaMonitor", "thermostatPackage", "filterUpgrade"],
    },
  },

  addons: {
    ductCleaning: {
      id: "ductCleaning",
      label: "Duct Cleaning",
      poolOnly: false,
      perSystem: false,
      basePrice: 650,
      sizeMultipliers: { small: 1.0, medium: 1.15, large: 1.3 },
      minPrice: 650,
      maxPrice: 1200,
    },
    bootSealing: {
      id: "bootSealing",
      label: "Boot Sealing",
      poolOnly: false,
      perSystem: true,
      pricePerSystem: 299,
      minPrice: 299,
      maxPrice: 900,
    },
    emporiaMonitor: {
      id: "emporiaMonitor",
      label: "Emporia Energy Monitor",
      poolOnly: false,
      perSystem: false,
      basePricePerPanel: 400,
      installPerPanel: 200,
      minPricePerPanel: 500,
      maxPricePerPanel: 800,
    },
    thermostatPackage: {
      id: "thermostatPackage",
      label: "Smart Thermostat Package",
      poolOnly: false,
      perSystem: false,
      types: { basic: 350, advanced: 550, premium: 850 },
      install: { standard: 150, complex: 300 },
      sensorPrice: 85,
      minPrice: 900,
      maxPrice: 2000,
      defaultType: "advanced",
      defaultInstall: "standard",
      defaultSensors: 3,
    },
    filterUpgrade: {
      id: "filterUpgrade",
      label: "4\" Filter / Plenum Upgrade",
      poolOnly: false,
      perSystem: true,
      pricePerSystem: 850,
      complexityAdj: { standard: 0, difficult: 150, premium: 200 },
      defaultComplexity: "standard",
      minPrice: 850,
      maxPrice: 3000,
    },
    poolPump: {
      id: "poolPump",
      label: "Variable-Speed Pool Pump",
      poolOnly: true,
      perSystem: false,
      types: { entry: 1800, mid: 2200, premium: 2600 },
      install: { standard: 600, complex: 1000 },
      sizeMultipliers: { small: 1.0, medium: 1.1, large: 1.2 },
      minPrice: 2500,
      maxPrice: 3800,
      defaultType: "mid",
      defaultInstall: "standard",
      defaultPoolSize: "medium",
    },
  },

  financeOptions: [
    { id: "cash", label: "Pay in Full", months: 0, apr: 0, badge: "Best Value", note: "No finance charge. Lowest total cost." },
    { id: "m3", label: "3 Months", months: 3, apr: 0.05, badge: "Same as Cash", note: "Pay over 3 months, minimal interest." },
    { id: "m6", label: "6 Months", months: 6, apr: 0.07, badge: null, note: "Pay over 6 months." },
    { id: "m12", label: "12 Months", months: 12, apr: 0.10, badge: null, note: "12-month installment plan." },
    { id: "m24", label: "24 Months", months: 24, apr: 0.14, badge: null, note: "24-month installment plan." },
    { id: "m36", label: "36 Months", months: 36, apr: 0.18, badge: null, note: "36-month installment plan." },
    { id: "m48", label: "48 Months", months: 48, apr: 0.22, badge: null, note: "48-month installment plan." },
    { id: "m60", label: "60 Months", months: 60, apr: 0.26, badge: "Lowest Monthly", note: "60-month installment plan." },
  ],

  disclaimers: {
    general: "Pricing, incentives, financing terms, and offers are subject to change.",
    savings: "Savings and scoring examples are illustrative only. Actual results vary.",
    finance: "Financing is subject to approval and actual lender terms.",
    property: "Property details may be estimated or imported and should be verified.",
    aeroseal: "Aeroseal statistics are sourced from Aeroseal published data and refer to the Aeroseal technology platform, not EG Comfort operating history.",
  },

  videos: [
    {
      id: "aeroseal-overview",
      title: "How Duct Sealing Works",
      caption: "A short visual explanation of the Aeroseal duct sealing process.",
      url: "https://www.youtube.com/embed/K3JAR0dCNhc",
      embedType: "iframe",
    },
  ],
};
